import { Geist, Geist_Mono } from "next/font/google";
import '@fortawesome/fontawesome-free/css/all.min.css';
import 'bootstrap/dist/css/bootstrap.min.css';
import "./globals.css";
import Header from "./Components/Header";
import Footer from "./Components/Footer/Footer";
import AnimationAos from "./Components/AnimationAos";
import ScrollToTop from "./Components/ScrollToTop/ScrollToTop";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Life Coach",
  description: "Generated by Marketopia",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <AnimationAos/>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ScrollToTop/>
        <Header/>
        <main>
        {children}
        </main>
        <Footer/>
      </body>
    </html>
  );
}
